10th commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,6 +29,10 @@ jobs:
             python -m pip install --upgrade pip
             pip install flake8 pytest tox tox-gh-actions
             pip install -r requirements.txt
+        - name: Confirm requirements_dev.txt exists
+          run: |
+            ls -la
+            cat requirements_dev.txt || echo "requirements_dev.txt not found"
         - name: Test with tox
           run: tox
 
